# Generated by Django 2.2.1 on 2019-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=999)),
                ('email', models.CharField(max_length=200)),
                ('agent', models.BooleanField()),
            ],
        ),
    ]
