# Generated by Django 2.2.1 on 2019-05-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('streetname', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('ssc', models.CharField(max_length=10)),
                ('credit_card', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=200)),
                ('new_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
