# Generated by Django 2.2.1 on 2019-05-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='new_property',
        ),
    ]
