# Generated by Django 2.2.1 on 2019-05-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_buyer_new_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card', models.CharField(max_length=16)),
                ('exp_date', models.DateField()),
                ('cvc', models.IntegerField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentBuyer',
        ),
    ]
