# Generated by Django 2.2.1 on 2019-05-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20190515_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='exp_date',
            field=models.CharField(max_length=5),
        ),
    ]
