# Generated by Django 2.2.1 on 2019-05-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20190515_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='buyer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer.Buyer'),
        ),
    ]
