# Generated by Django 2.2.1 on 2019-05-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_auto_20190515_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer'),
        ),
    ]
