# Generated by Django 2.2.1 on 2019-05-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_auto_20190515_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='buyer',
        ),
        migrations.AddField(
            model_name='buyer',
            name='credit_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.CreditCard'),
        ),
    ]
