# Generated by Django 2.2.1 on 2019-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_buyersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyersession',
            name='buyer',
        ),
        migrations.AddField(
            model_name='buyersession',
            name='search_term',
            field=models.CharField(default='bla', max_length=200),
            preserve_default=False,
        ),
    ]
