# Generated by Django 2.2.1 on 2019-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_buyersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='country',
            field=models.CharField(choices=[('ICELAND', 'Iceland'), ('UNITED STATES', 'United States'), ('SPAIN', 'Spain'), ('ITALY', 'Italy'), ('ENGLAND', 'England'), ('GERMANY', 'Germany'), ('THE BAHAMAS', 'The Bahamas'), ('CARRIBEAN', 'Carribean')], max_length=10),
        ),
    ]
