# Generated by Django 2.2.1 on 2019-05-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_auto_20190516_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyersession',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.Buyer'),
        ),
    ]
