# Generated by Django 2.2.1 on 2019-05-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_auto_20190516_1147'),
        ('buyer', '0010_auto_20190516_2323'),
    ]

    operations = [
    ]
