# Generated by Django 2.2.1 on 2019-05-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_auto_20190516_2043'),
        ('buyer', '0009_auto_20190516_1147'),
        ('buyer', '0011_auto_20190516_2145'),
    ]

    operations = [
    ]
