# Generated by Django 2.2.1 on 2019-05-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_merge_20190517_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyersession',
            name='session',
        ),
    ]
