# Generated by Django 2.2.1 on 2019-05-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20190515_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='on_sale',
            field=models.BooleanField(null=True),
        ),
    ]
