# Generated by Django 2.2.1 on 2019-05-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20190515_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
