# Generated by Django 2.2.1 on 2019-05-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20190515_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='on_sale',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
