# Generated by Django 2.2.1 on 2019-05-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20190515_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='on_sale',
            field=models.BooleanField(null=True),
        ),
    ]
