# Generated by Django 2.2.1 on 2019-05-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20190516_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(choices=[('ICELAND', 'Iceland'), ('UNITED STATES', 'United States'), ('SPAIN', 'Spain'), ('ITALY', 'Italy'), ('ENGLAND', 'England'), ('GERMANY', 'Germany'), ('THE BAHAMAS', 'The Bahamas'), ('CARRIBEAN', 'Carribean')], max_length=8),
        ),
    ]
