# Generated by Django 2.2.1 on 2019-05-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20190516_2041'),
        ('property', '0022_auto_20190516_2143'),
    ]

    operations = [
    ]
